backend:
  name: auth0
  repo: ethanbaileyhomework/website-food-truck
  branch: main
  auth0:
    # The Auth0 credentials are injected at runtime by the admin config API route.
    client_id: ""
    auth_domain: ""

media_folder: "public/uploads"
public_folder: "/uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "site_settings"
    label: "Site Settings"
    file: "content/site-settings.yaml"
    editor:
      preview: false
    fields:
      - { label: "Site Name", name: "siteName", widget: "string" }
      - { label: "Tagline", name: "siteTagline", widget: "string", required: false }
      - { label: "Logo", name: "logo", widget: "image", required: false }
      - { label: "Primary Color", name: "primaryColor", widget: "color", default: "#C3423F" }
      - label: "Contact"
        name: "contact"
        widget: "object"
        fields:
          - { label: "Email", name: "email", widget: "string", required: false }
          - { label: "Phone", name: "phone", widget: "string", required: false }
          - { label: "Address", name: "address", widget: "string", required: false }
          - { label: "ABN", name: "abn", widget: "string", required: false }
      - label: "Social Links"
        name: "socials"
        widget: "object"
        fields:
          - { label: "Facebook", name: "facebook", widget: "string", required: false }
          - { label: "Instagram", name: "instagram", widget: "string", required: false }
          - { label: "YouTube", name: "youtube", widget: "string", required: false }
          - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
          - { label: "TikTok", name: "tiktok", widget: "string", required: false }
          - { label: "Twitter/X", name: "twitter", widget: "string", required: false }
      - label: "Bank Details"
        name: "bank"
        widget: "object"
        fields:
          - { label: "Account Name", name: "accountName", widget: "string", required: false }
          - { label: "BSB", name: "bsb", widget: "string", required: false }
          - { label: "Account Number", name: "accountNumber", widget: "string", required: false }
          - { label: "Reference", name: "reference", widget: "string", required: false }
      - label: "Donate Links"
        name: "donate"
        widget: "object"
        fields:
          - { label: "PayPal Donate URL", name: "paypal", widget: "string", required: false }
          - { label: "Stripe Checkout URL", name: "stripe", widget: "string", required: false }
          - { label: "Donation Note", name: "note", widget: "text", required: false }
      - label: "Map"
        name: "map"
        widget: "object"
        fields:
          - { label: "Google Maps Embed URL", name: "embedUrl", widget: "text", required: false }
          - { label: "Directions URL", name: "directionsUrl", widget: "string", required: false }
      - label: "Service"
        name: "service"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Days", name: "days", widget: "string", required: false }
          - { label: "Time", name: "time", widget: "string", required: false }
          - { label: "Location", name: "location", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { label: "Phone", name: "phone", widget: "string", required: false }
          - { label: "Email", name: "email", widget: "string", required: false }
          - label: "Notes"
            name: "notes"
            widget: "list"
            field: { label: "Note", name: "note", widget: "string" }
          - { label: "Directions Button Label", name: "ctaLabel", widget: "string", required: false }
      - label: "Looker Studio"
        name: "lookers"
        widget: "object"
        fields:
          - { label: "Dashboard URL", name: "statsUrl", widget: "string", required: false }
          - { label: "Embed Title", name: "embedTitle", widget: "string", required: false }
      - { label: "Tally Form URL", name: "tallyFormUrl", widget: "string", required: false }
      - label: "Analytics"
        name: "analytics"
        widget: "object"
        fields:
          - { label: "GA4 Measurement ID", name: "gaMeasurementId", widget: "string", required: false }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Default Description", name: "defaultDescription", widget: "text", required: false }
          - { label: "Open Graph Image", name: "ogImage", widget: "image", required: false }
  - name: "home"
    label: "Home Page"
    file: "content/home.yaml"
    editor:
      preview: false
    fields:
      - label: "Hero"
        name: "hero"
        widget: "object"
        fields:
          - { label: "Eyebrow", name: "eyebrow", widget: "string", required: false }
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Subheadline", name: "subheadline", widget: "text", required: false }
          - { label: "Hero Image", name: "image", widget: "image", required: false }
          - label: "CTAs"
            name: "ctas"
            widget: "object"
            fields:
              - label: "Primary"
                name: "primary"
                widget: "object"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Link", name: "href", widget: "string" }
              - label: "Secondary"
                name: "secondary"
                widget: "object"
                required: false
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Link", name: "href", widget: "string" }
      - label: "What We Do"
        name: "whatWeDo"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text", required: false }
          - label: "Cards"
            name: "cards"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Icon", name: "icon", widget: "select", options: ["bowl", "basket", "hands"], default: "bowl" }
      - label: "Impact"
        name: "impact"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Carousel"
        name: "carousel"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Role", name: "role", widget: "string", required: false }
              - { label: "Image", name: "image", widget: "image", required: false }
      - label: "SEO"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "text", required: false }
  - name: "stats_settings"
    label: "Stats Settings"
    file: "content/stats-settings.yaml"
    editor:
      preview: false
    fields:
      - label: "Google Sheet"
        name: "sheet"
        widget: "object"
        fields:
          - { label: "CSV URL", name: "csvUrl", widget: "string", required: false }
          - label: "Field Mapping"
            name: "fieldMapping"
            widget: "object"
            fields:
              - { label: "Date Column", name: "date", widget: "string" }
              - { label: "Meals Column", name: "meals", widget: "string" }
              - { label: "Guests Column", name: "guests", widget: "string" }
              - { label: "Volunteers Column", name: "volunteers", widget: "string" }
              - { label: "Groceries Column", name: "groceries", widget: "string" }
              - { label: "Notes Column", name: "notes", widget: "string", required: false }
          - { label: "Service Date Format", name: "serviceDateFormat", widget: "string", required: false }
      - label: "Fallback Totals"
        name: "fallbackTotals"
        widget: "object"
        fields:
          - { label: "Meals", name: "meals", widget: "number" }
          - { label: "Guests", name: "guests", widget: "number" }
          - { label: "Volunteers", name: "volunteers", widget: "number" }
          - { label: "Groceries", name: "groceries", widget: "number" }
          - { label: "Services", name: "services", widget: "number" }
      - label: "Fallback Latest Service"
        name: "fallbackLatestService"
        widget: "object"
        fields:
          - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
          - { label: "Meals", name: "meals", widget: "number" }
          - { label: "Guests", name: "guests", widget: "number" }
          - { label: "Volunteers", name: "volunteers", widget: "number" }
          - { label: "Groceries", name: "groceries", widget: "number" }
          - { label: "Notes", name: "notes", widget: "text", required: false }
      - label: "Looker Studio"
        name: "lookers"
        widget: "object"
        required: false
        fields:
          - { label: "Dashboard URL", name: "statsUrl", widget: "string", required: false }
          - { label: "Embed Title", name: "embedTitle", widget: "string", required: false }
      - label: "SEO"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "text", required: false }
  - name: "about"
    label: "About Page"
    file: "content/about.yaml"
    editor:
      preview: false
    fields:
      - label: "Story"
        name: "story"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Mission & Vision"
        name: "missionVision"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Mission", name: "mission", widget: "text" }
          - { label: "Vision", name: "vision", widget: "text" }
      - label: "Impact"
        name: "impact"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Points"
            name: "points"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
      - label: "Partnerships"
        name: "partnerships"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
      - label: "Future Plans"
        name: "futurePlans"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "SEO"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "text", required: false }
  - name: "donate"
    label: "Donate Page"
    file: "content/donate.yaml"
    editor:
      preview: false
    fields:
      - { label: "Intro Title", name: "introTitle", widget: "string" }
      - { label: "Intro Body", name: "introBody", widget: "markdown" }
      - label: "SEO"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "text", required: false }
  - name: "volunteer"
    label: "Volunteer Page"
    file: "content/volunteer.yaml"
    editor:
      preview: false
    fields:
      - { label: "Intro Title", name: "introTitle", widget: "string" }
      - { label: "Intro Body", name: "introBody", widget: "markdown" }
      - label: "SEO"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "text", required: false }
  - name: "sponsors"
    label: "Sponsors Page"
    file: "content/sponsors.yaml"
    editor:
      preview: false
    fields:
      - { label: "Intro Title", name: "introTitle", widget: "string" }
      - { label: "Intro Body", name: "introBody", widget: "markdown" }
      - label: "SEO"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "text", required: false }
  - name: "team"
    label: "Team"
    label_singular: "Team member"
    folder: "content/team"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Headshot", name: "headshot", widget: "image", required: false }
      - { label: "Display Order", name: "order", widget: "number", required: false }
      - { label: "Bio", name: "body", widget: "markdown", required: false }
  - name: "stories"
    label: "Stories"
    folder: "content/stories"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Cover Image", name: "coverImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "partners"
    label: "Partners"
    folder: "content/partners"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Website", name: "link", widget: "string", required: false }
      - { label: "Logo", name: "logo", widget: "image", required: false }
      - { label: "Blurb", name: "blurb", widget: "markdown", required: false }
      - { label: "Category", name: "category", widget: "select", options: ["sponsor", "partner"], required: false }
      - { label: "Display Order", name: "order", widget: "number", required: false }
